# Generated by Django 4.2.16 on 2024-12-03 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
