# Generated by Django 4.2.16 on 2024-12-04 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (
                    (
                        "can_view_library_loaned_books",
                        "View all loaned books from library",
                    ),
                ),
            },
        ),
    ]
